//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvcpro.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cinema_appContext : DbContext
    {
        public cinema_appContext()
            : base("name=cinema_appContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cinema> cinemas { get; set; }
        public virtual DbSet<movy> movies { get; set; }
        public virtual DbSet<show> shows { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
    }
}
