//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvcpro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ticket_id { get; set; }
        public string seatno { get; set; }
        public int show_id { get; set; }
        public int ticket_price { get; set; }
    
        public virtual show show { get; set; }
    }
}
